name: Auto

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: npm run deploy
        
        - name: Deploy
      uses: 
      with:
        server: 
        username: P2004408156 
        password: 
